=== Ann-Geo/StreamSim/config/tunables/rabbitmq_tunables_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Messaging System Configuration",
    "type": "object",
    "properties": {
      "Acknowledgements": {
        "type": "object",
        "properties": {
          "PublisherConfirms": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": [
                  "no_acks",
                  "individual_async",
                  "batch_sync",
                  "individual_sync"
                ]
              },
              "batchSize": {
                "type": "integer",
                "minimum": 1,
                "description": "Number of messages in each batch (only valid if type is 'batch_sync')"
              }
            },
            "required": ["type"],
            "allOf": [
              {
                "if": {
                  "properties": {
                    "type": {
                      "enum": ["batch_sync"]
                    }
                  }
                },
                "then": {
                  "required": ["batchSize"]
                },
                "else": {
                  "not": {
                    "required": ["batchSize"]
                  }
                }
              }
            ]
          },
          "ConsumerAcks": {
            "type": "object",
            "properties": {
              "mode": {
                "type": "string",
                "enum": ["automatic", "manual"]
              },
              "manualAckType": {
                "type": "string",
                "enum": ["single", "multiple"]
              },
              "manualAckMultipleCount": {
                "type": "integer",
                "minimum": 1,
                "description": "Number of messages after which to send a multiple manual ack (only used when manualAckType is 'multiple')"
              }
            },
            "required": ["mode"],
            "allOf": [
              {
                "if": {
                  "properties": {
                    "mode": { "const": "manual" } 
                  },
                    "required": ["mode"]
                  },
                  "then": {
                    "required": ["manualAckType"]
                  }
                },
               {
                "if": {
                  "properties": {
                    "mode": { "const": "manual" },
                    "manualAckType": { "const": "multiple" }
                  },
                  "required": ["mode", "manualAckType"]
                },
                "then": {
                  "required": ["manualAckMultipleCount"]
                }
              },
              {
                "if": {
                  "properties": {
                    "mode": { "not": { "const": "manual" } }
                  },
                  "required": ["mode"]
                },
                "then": {
                  "not": {
                    "required": ["manualAckType","manualAckMultipleCount"]
                  }
                }
              }
            ]
          }
        },
        "required": ["PublisherConfirms", "ConsumerAcks"]
      },
      "Durability": {
        "type": "object",
        "properties": {
          "MessageDurability": {
            "type": "string",
            "enum": ["none", "persistent"]
          },
          "QueueDurability": {
            "type": "string",
            "enum": ["none", "persistent"]
          }
        },
        "required": ["MessageDurability", "QueueDurability"]
      },
      "PrefetchCount": {
        "type": "object",
        "properties": {
          "PerConsumer": {
            "type": "integer",
            "minimum": 0
          }
        },
        "required": ["PerConsumer"],
        "additionalProperties": false
      },
      "QueueProperties": {
        "type": "object",
        "properties": {
          "QueueSizeMessages": {
            "type": "integer",
            "minimum": 1,
            "description": "Maximum number of messages allowed in the queue, represented in bytes"
          },
          "QueueOverflow": {
            "type": "string",
            "enum": ["drop-head", "dead-letter", "reject-publish"],
            "description": "Queue overflow strategy"
          },
          "QueueStructure": {
            "type": "string",
            "enum": ["classic", "quorum", "stream"],
            "description": "Type of queue structure to use"
          }
        }
      },
      "BindingDurability": {
        "type": "string",
        "enum": ["fully_durable", "semi_durable", "fully_transient"]
      },
      "TotalQueues": {
        "type": "integer",
        "minimum": 1,
        "description": "Total number of queues allocated"
      },
      "StreamUseCase": {
        "type": "object",
        "properties": {
          "MaxLength": {
            "type": "integer",
            "minimum": 1024
          },
          "MaxSegmentSizeBytes": {
            "type": "integer",
            "minimum": 1
          }
        }
      }
    }
  }

=== Ann-Geo/StreamSim/config/tunables/generic/combination_adv/rmq_tunable_ind_sync.json
{
  "Acknowledgements": {
    "PublisherConfirms": {
      "type": "batch_sync",
      "batchSize": 16
    },
    "ConsumerAcks": {
      "mode": "manual",
      "manualAckType": "multiple",
      "manualAckMultipleCount": 16
    }
  },
  "Durability": {
    "MessageDurability": "none",
    "QueueDurability": "none"
  },
  "PrefetchCount": {
    "PerConsumer": 16
  },
  "QueueProperties": {
    "QueueStructure": "classic",
    "QueueSizeMessages": 131072,
    "QueueOverflow": "reject-publish"
  },
  "BindingDurability": "fully_durable",
  "TotalQueues": 1,
  "StreamUseCase": {
    "MaxLength": 2048,
    "MaxSegmentSizeBytes": 4096
  }
}

=== Ann-Geo/StreamSim/config/tunables/lcls/pub_acks/rmq_tunable_no_acks.json
{
  "Acknowledgements": {
    "PublisherConfirms": {
      "type": "no_acks"
    },
    "ConsumerAcks": {
      "mode": "automatic"
    }
  },
  "Durability": {
    "MessageDurability": "none",
    "QueueDurability": "none"
  },
  "PrefetchCount": {
    "PerConsumer": 1
  },
  "QueueProperties": {
    "QueueStructure": "classic",
    "QueueSizeMessages": 131072,
    "QueueOverflow": "reject-publish"
  },
  "BindingDurability": "fully_durable",
  "TotalQueues": 1,
  "StreamUseCase": {
    "MaxLength": 131072,
    "MaxSegmentSizeBytes": 4096
  }
}

=== Ann-Geo/StreamSim/config/tunables/deleria/cons_acks/rmq_tunable_manual_64pre_2ack.json
{
  "Acknowledgements": {
    "PublisherConfirms": {
      "type": "no_acks"
    },
    "ConsumerAcks": {
      "mode": "manual",
      "manualAckType": "multiple",
      "manualAckMultipleCount": 2
    }
  },
  "Durability": {
    "MessageDurability": "none",
    "QueueDurability": "none"
  },
  "PrefetchCount": {
    "PerConsumer": 64
  },
  "QueueProperties": {
    "QueueSizeMessages": 131072,
    "QueueOverflow": "drop-head"
  },
  "BindingDurability": "fully_durable",
  "TotalQueues": 1,
  "StreamUseCase": {
    "MaxLength": 2048,
    "MaxSegmentSizeBytes": 4096
  }
}

=== Ann-Geo/StreamSim/config/tunables/deleria/pub_acks/rmq_tunable_batch_sync_2.json
{
  "Acknowledgements": {
    "PublisherConfirms": {
      "type": "batch_sync",
      "batchSize": 2
    },
    "ConsumerAcks": {
      "mode": "automatic"
    }
  },
  "Durability": {
    "MessageDurability": "none",
    "QueueDurability": "none"
  },
  "PrefetchCount": {
    "PerConsumer": 1
  },
  "QueueProperties": {
    "QueueSizeMessages": 131072,
    "QueueOverflow": "drop-head"
  },
  "BindingDurability": "fully_durable",
  "TotalQueues": 1,
  "StreamUseCase": {
    "MaxLength": 2048,
    "MaxSegmentSizeBytes": 4096
  }
}

=== Ann-Geo/StreamSim/config/tunables/deleria/cons_acks/rmq_tunable_manual_single.json
{
  "Acknowledgements": {
    "PublisherConfirms": {
      "type": "no_acks"
    },
    "ConsumerAcks": {
      "mode": "manual",
      "manualAckType": "single"
    }
  },
  "Durability": {
    "MessageDurability": "none",
    "QueueDurability": "none"
  },
  "PrefetchCount": {
    "PerConsumer": 1
  },
  "QueueProperties": {
    "QueueSizeMessages": 131072,
    "QueueOverflow": "drop-head"
  },
  "BindingDurability": "fully_durable",
  "TotalQueues": 1,
  "StreamUseCase": {
    "MaxLength": 2048,
    "MaxSegmentSizeBytes": 4096
  }
}

=== Ann-Geo/StreamSim/config/tunables/rmq_tunable_example1.json
{
  "Acknowledgements": {
    "PublisherConfirms": {
      "type": "individual_sync"
    },
    "ConsumerAcks": {
      "mode": "automatic"
    }
  },
  "Durability": {
    "MessageDurability": "persistent",
    "QueueDurability": "persistent"
  },
  "PrefetchCount": {
    "PerConsumer": 1
  },
  "QueueProperties": {
    "QueueStructure": "quorum",
    "QueueSizeMessages": 10,
    "QueueOverflow": "reject-publish"
  },
  "BindingDurability": "fully_durable",
  "TotalQueues": 1,
  "StreamUseCase": {
    "MaxLength": 2048,
    "MaxSegmentSizeBytes": 4096
  }
}

=== Ann-Geo/StreamSim/config/tunables/lcls/prefetch_count/rmq_tunable_32.json
{
  "Acknowledgements": {
    "PublisherConfirms": {
      "type": "no_acks"
    },
    "ConsumerAcks": {
      "mode": "manual",
      "manualAckType": "single"
    }
  },
  "Durability": {
    "MessageDurability": "none",
    "QueueDurability": "none"
  },
  "PrefetchCount": {
    "PerConsumer": 32
  },
  "QueueProperties": {
    "QueueStructure": "classic",
    "QueueSizeMessages": 131072,
    "QueueOverflow": "reject-publish"
  },
  "BindingDurability": "fully_durable",
  "TotalQueues": 1,
  "StreamUseCase": {
    "MaxLength": 2048,
    "MaxSegmentSizeBytes": 4096
  }
}

=== Ann-Geo/StreamSim/config/tunables/lcls/durability/rmq_tunable_ind_sync_persistent.json
{
  "Acknowledgements": {
    "PublisherConfirms": {
      "type": "individual_sync"
    },
    "ConsumerAcks": {
      "mode": "automatic"
    }
  },
  "Durability": {
    "MessageDurability": "persistent",
    "QueueDurability": "none"
  },
  "PrefetchCount": {
    "PerConsumer": 1
  },
  "QueueProperties": {
    "QueueStructure": "classic",
    "QueueSizeMessages": 131072,
    "QueueOverflow": "reject-publish"
  },
  "BindingDurability": "fully_durable",
  "TotalQueues": 1,
  "StreamUseCase": {
    "MaxLength": 2048,
    "MaxSegmentSizeBytes": 4096
  }
}
