=== Ann-Geo/StreamSim/config/workload/workload_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/workload.schema.json",
    "title": "Workload",
    "description": "Schema for workload characteristics",
    "type": "object",
    "properties": {
      "WorkloadName": {
        "type": "string",
        "enum": ["deleria", "lcls", "mock"],
        "description": "Workload name (deleria, lcls, mock)"
      },
      "PayloadSize": {
        "type": "integer",
        "minimum": 1,
        "description": "Payload size in bytes"
      },
      "PayloadFormat": {
        "type": "string",
        "enum": ["plaintext", "json", "binary", "hdf5"],
        "description": "Format of the payload (plaintext, json, binary, hdf5)"
      },
      "PayloadElement": {
        "type": "string",
        "enum": ["image", "file", "variable"],
        "description": "Type of the payload element (e.g., image, file, variable)"
      },
      "DataRate": {
        "type": "integer",
        "minimum": 1,
        "description": "Data rate in KB/s"
      },
      "DataPackaging": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": ["batched", "individual"],
            "description": "Packaging of the data (batched vs. individual)"
          },
          "batchMessageCount": {
            "type": "integer",
            "minimum": 1,
            "description": "Number of messages per batch (only required if type is 'batched')"
          }
        },
        "required": ["type"],
        "allOf": [
          {
            "if": {
              "properties": { "type": { "const": "batched" } }
          },
            "then": {
              "required": ["batchMessageCount"]
          },
            "else": {
              "not": {
                "required": ["batchMessageCount"]
              }
            }
          }
        ]
      },
      "Variability": {
        "type": "string",
        "enum": ["burst", "steady", "fluctuating"],
        "description": "Variability of the workload (burst, steady, fluctuating)"
      },
      "ConsumptionMode": {
        "type": "string",
        "enum": ["push", "pull"],
        "description": "Mode of consumption (push or pull)"
      },
      "NumConsumers": {
        "type": "integer",
        "minimum": 1,
        "description": "Number of consumers"
      },
      "ConsumerParallelism": {
        "type": "string",
        "enum": ["dedicatedMPI", "nonMPI"],
        "description": "Type of consumer parallelism (centralMPI, dedicatedMPI, nonMPI)"
      },
      "ConsPayloadDistribution": {
        "type": "string",
        "enum": ["roundrobin", "random", "broadcast"],
        "description": "Consumer payload distribution (roundrobin or random)"
      },
      "NumProducers": {
        "type": "integer",
        "minimum": 1,
        "description": "Number of producers"
      },
      "ProducerParallelism": {
        "type": "string",
        "enum": ["nonMPI", "dedicatedMPI"],
        "description": "Type of producer parallelism (nonMPI)"
      }
    },
    "required": [
      "WorkloadName",
      "PayloadSize",
      "DataRate",
      "NumConsumers",
      "NumProducers"
    ]
  }

=== Ann-Geo/StreamSim/config/workload/deleria/2/deleria.json
{
    "WorkloadName": "deleria",
    "PayloadSize": 2000,
    "PayloadFormat": "binary",
    "PayloadElement": "variable",
    "DataRate": 4000000,
    "DataPackaging": {
        "type": "batched",
        "batchMessageCount": 8
    },
    "Variability": "steady",
    "ConsumptionMode": "push",
    "NumConsumers": 2, 
    "ConsumerParallelism": "nonMPI",
    "ConsPayloadDistribution": "roundrobin",
    "NumProducers": 2,
    "ProducerParallelism": "nonMPI"
  }

=== Ann-Geo/StreamSim/config/workload/lcls/2/lcls.json
{
    "WorkloadName": "lcls",
    "PayloadSize": 1000000,
    "PayloadFormat": "hdf5",
    "PayloadElement": "file",
    "DataRate": 3750000,
    "DataPackaging": {
    "type": "individual"
  },
    "Variability": "steady",
    "ConsumptionMode": "push", 
    "NumConsumers": 2, 
    "ConsumerParallelism": "dedicatedMPI",
    "ConsPayloadDistribution": "roundrobin",
    "NumProducers": 2,
    "ProducerParallelism": "dedicatedMPI"
  }

=== Ann-Geo/StreamSim/config/workload/mock_workload.json
{
  "WorkloadName": "mock",
  "PayloadSize": 1000000,
  "PayloadFormat": "plaintext",
  "PayloadElement": "file",
  "DataRate": 10000,
  "DataPackaging": {
    "type": "individual"
  },
  "Variability": "steady",
  "ConsumptionMode": "pull",
  "NumConsumers": 4,
  "ConsumerParallelism": "dedicatedMPI",
  "ConsPayloadDistribution": "roundrobin",
  "NumProducers": 4,
  "ProducerParallelism": "dedicatedMPI"
}
